import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import Partners from '../components/partners'
import Schedule from '../components/schedule'
import Speakers from '../components/speakers'
import { AppDispatch } from '../store'
import { fetchData } from '../store/actions'
import styles from '../styles/Home.module.css'

export default function Home() {
  
  const dispatch: AppDispatch = useDispatch();

  useEffect(()=>{
    dispatch(fetchData())
  }, [dispatch])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Ponentes</h2>
        <Speakers/>
        <h2>Charlas</h2>
        <Schedule/>
        <h2>Patrocinadores</h2>
        <Partners/>
      </main>
    </div>
  )
}